# Generated by Django 5.2.4 on 2025-07-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_price_productcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
