# Generated by Django 5.2.4 on 2025-08-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_supplier_email_product_supplier_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplier_email',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier_name',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='supplier_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
